title: Vaibhav Jaisingpure
logo: https://cdn1.iconfinder.com/data/icons/seo-and-web-development-color/64/seo-and-web-development-05-512.png
description: Page shows the project done in python languages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
