title: <p align="center"> <h5>Vaibhav Jaisingpure</h5> </p>
logo: https://th.bing.com/th/id/OIP.64rMqAZTKuVb2NWkyqMehgAAAA?pid=ImgDet&w=238&h=250&rs=1

description:
  <p class="description" align="center">
  <a href="https://www.linkedin.com/in/vaibhav-jaisingpure-0107b6183/">LinkedIn</a> |
  <a href="https://github.com/vibz96">GitHub</a>
  
  <br>   
  This page shows the project i've done while learning python language.
  <br>
  </p>



remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
